version: "3.9"
services:
  video-translator:
    image: video-translator
    ports:
      - "7860:7860"
      - "8081:8081"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
