version: "3.9"
services:
  video-translator:
    image: zeroprg/video-translator
    ports:
      - "7860:7860"
      - "8081:8081"
    volumes:
      - ./app/downloads:/app/downloads
      - ./app/translations:/app/translations  
    environment:
      - LANG=C.UTF-8 
      - DOWNLOAD_FOLDER=/app/downloads
      - TRANSLATIONS_FOLDER=/app/translations
    networks:
      - my-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  ollama:
