version: "3.9"
services:
  video-translator:
    image: video-translator
    ports:
      - "7860:7860"
      - "8081:8081"
    volumes:
      - ./app/downloads:/app/downloads
      - ./app/translations:/app/translations  
    environment:
      - DOWNLOAD_FOLDER=/app/downloads
      - TRANSLATIONS_FOLDER=/app/translate
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
